      SUBROUTINE A6BS(A,NA,N,NP)
C  ALGORITHM 6
C  J.C. NASH   JULY 1978, APRIL 1989
C  BACK-SUBSTITUTION TO FOLLOW GAUSS ELIMINATION
C     A=WORKING ARRAY AS OUTPUT BY A5GE - ALGORITHM 5
C     NA=FIRST DIMENSION OF A
C     NP=N + NO. OF (TRANSFORMED) RIGHT HAND SIDES
C     N=ORDER OF EQUATIONS
C  STEP 0
      INTEGER N,NA,NP,N1,I,J,JJ,K
      REAL A(NA,NP),S
C  STEP 1
      N1=N+1
      DO 200 I=N1,NP
C  STEP 2
        A(N,I)=A(N,I)/A(N,N)
        IF(N.EQ.1)GOTO 200
C  STEP 3 - NOTE FORM FOR LOOPING
        DO 180 JJ=2,N
          J=N1-JJ
C  STEP 4
          S=A(J,I)
C  STEP 5
          J1=J+1
          DO 160 K=J1,N
            S=S-A(J,K)*A(K,I)
 160      CONTINUE
C  STEP 6
          A(J,I)=S/A(J,J)
C  STEP 7
 180    CONTINUE
C  STEP 8
 200  CONTINUE
      RETURN
      END

