      SUBROUTINE A5GE(A,NA,N,NP,D,TOL)
C   ALGORITHM 5
C  J.C. NASH   JULY 1978, FEBRUARY 1980, APRIL 1989
C   GAUSS ELIMINATION WITH PARTIAL PIVOTING
C     A=WORKING ARRAY -- COLUMNS 1 TO N HAVE COEFFICIENT MATRIX
C                     -- COLUMNS N+1 TO NP HAVE RIGHT HAND SIDES
C     NA=FIRST DIMENSION OF A .GE. N
C     N=ORDER OF EQUATIONS
C     NP=N + NO. OF RIGHT HAND SIDES
C     D=DETERMINANT OF COEFFICIENT MATRIX (OUTPUT ONLY)
C     TOL=TOLERANCE FOR ZERO SCALED TO SIZE OF COEFFICINT ELEMENTS
C        TOL IS SET NEGATIVE IF COEFFICIENT MATRIX COMPUTATIONALLY
C        SINGULAR. NEGATIVE TOL ON INPUT STOPS EXECUTION
C  STEP 0
      INTEGER N,NA,NP,I,N1,J,H,K,J1
      REAL D,TOL,A(NA,NP),S
      D=1.0
      IF(TOL.LE.0.0)STOP
C  STEP 1
      N1=N-1
      DO 60 J=1,N1
C  STEP 2A
        S=ABS(A(J,J))
        K=J
C  STEP 2B
        J1=J+1
        DO 10 H=J1,N
          IF(ABS(A(H,J)).LE.S)GOTO 10
          S=ABS(A(H,J))
          K=H
  10    CONTINUE
        IF(K.EQ.J)GOTO 30
C  STEP 3
        DO 20 I=J,NP
          S=A(K,I)
          A(K,I)=A(J,I)
          A(J,I)=S
  20    CONTINUE
        D=-D
C  STEP 4
  30    D=D*A(J,J)
        IF(ABS(A(J,J)).LE.TOL)GOTO 70
C  STEP 5
        DO 50 K=J1,N
          A(K,J)=A(K,J)/A(J,J)
          DO 40 I=J1,NP
            A(K,I)=A(K,I)-A(K,J)*A(J,I)
  40      CONTINUE
  50    CONTINUE
C  STEP 6
  60  CONTINUE
C  STEP 7
      D=D*A(N,N)
      IF(ABS(A(N,N)).LE.TOL)GOTO 70
      RETURN
C  COMPUTATIONALLY SINGULAR COEFFICIENT MATRIX -- EXIT WITH TOL.LT.0.0
  70  TOL=-1.0
      RETURN
      END

