      SUBROUTINE A18RF(U,V,COUNT,NBIS,FUN,TOL,NOCOM,IPR)
C  ALGORITHM 18
C  J.C. NASH   JULY 1978, FEBRUARY 1980, APRIL 1989
C  BISECTION  FALSE-POSITION ROOTFINDER
C  U,V DEFINE INTERVAL OF INTEREST
C  ON OUTPUT ROOT IS AT U,  FUN(U)=V
C  COUNT = LIMIT ON FUNCTION EVALUATIONS (INPUT)
C        = NO. OF EVALUATIONS USED (OUTPUT)
C  NBIS = INTERVAL BETWEEN BISECTIONS - BISECTION PERFORMED
C         EVERY NBIS STEPS
C  FUN = NAME OF FUNCTION
C     CALLING SEQUENCE    FVAL=FUN(X,NOCOM)
C  NOCOM=LOGICAL FLAG SET .TRUE. IF ALGORITHM CANNOT PROCEED
C  TOL = CONVERGENCE TOLERANCE ON LENGTH OF INTERVAL - STEP 9A
C  IPR = PRINTER CHANNEL -- NO OUTPUT UNLESS IPR.GT.0
      LOGICAL NOCOM
      INTEGER COUNT,LIMIT,NBIS,IPR,NBC
      REAL U,V,TOL,FU,FV,B,FB
C  STEP 0
      LIMIT=COUNT
      COUNT=0
      NOCOM=.FALSE.
      COUNT=COUNT+1
      FU=FUN(U,NOCOM)
      IF(NOCOM)RETURN
      FV=FUN(V,NOCOM)
      COUNT=COUNT+1
      IF(NOCOM)RETURN
C  STEP 1
      IF(FU*FV.GT.0.0)NOCOM=.TRUE.
C  ALTERNATIVE USES SIGN FUNCTION TO AVOID UNDERFLOW
      IF(NOCOM)RETURN
C  STEP 2
  20  B=(U*FV-V*FU)/(FV-FU)
C  STEP 3
  30  IF(B.GT.U)GOTO 40
      B=U
      V=FU
      RETURN
  40  IF(B.LT.V)GOTO 50
C  STEP 4
C  QUESTION .LE..GE. STEPS 3 + 4 OF MS. SEEMS WRONG
      U=V
      V=FV
      RETURN
C  STEP 5
  50  IF(IPR.GT.0)WRITE(IPR,970)COUNT,U,FU,V,FV
      COUNT=COUNT+1
 970  FORMAT(1H ,I4,11H EVALNS, F(,1PE16.8,2H)=,E16.8,4H  F(,E16.8,
     *2H)=,E16.8)
      IF(COUNT.GT.LIMIT)GOTO 110
      FB=FUN(B,NOCOM)
      IF(NOCOM)RETURN
C  STEP 6
      IF(FB*FU.GT.0.0)GOTO 80
C  STEP 7
      FV=FB
      V=B
      GOTO 90
C  STEP 8
  80  FU=FB
      U=B
C  STEP 9A
  90  IF((V-U).GT.TOL)GOTO 95
      V=FU
      RETURN
 95   NBC=(COUNT-2)/NBIS
      IF(NBIS*NBC.NE.(COUNT-2))GOTO 20
C  STEP 10
      IF(IPR.GT.0)WRITE(IPR,971)COUNT
 971  FORMAT(' BISECTION AT EVALN #',I5)
      B=U+(V-U)*0.5
      GOTO 30
C  NOTE ACTION IN CASE OF FUNCTION EVALUATION OVER-RUN
 110  NOCOM=.TRUE.
      COUNT=LIMIT
      V=FU
      RETURN
      END
