      SUBROUTINE A24CG(N,B,C,TOL,G,IPR,APR,V,T,IMULT)
C  ALGORITHM 24 CONJUGATE GRADIENT SOLUTION OF LINEAR EQUATIONS
C    HAVING POSITIVE DEFINITE COEFFICIENT MATRIX
C  J.C. NASH   JULY 1978, FEBRUARY 1980, APRIL 1989
C  N     = ORDER OF PROBLEM AND LENGTH OF VECTORS B,C,G,V,T
C  B     = INITIAL GUESS FOR SOLUTION (INPUT) MAY BE NULL
C        = SOLUTION (OUTPUT)
C  C     = RIGHT HAND SIDE OF EQUATIONS
C  TOL   = CONVERGENCE TOLERANCE ON SIZE OF RESIDUAL SUM OF SQUARES
C  G     = VECTOR OF APPROXIMATE RESIDUALS (OUTPUT)
C  IPR   = PRINTER CHANNEL. IF IPR.GT.0 PRINT TO CHANNEL IPR
C  APR   = NAME OF SUBROUTINE TO PUT A*T IN V
C         CALLING SEQUENCE:   CALL APR(N,T,V)
C  V,T   = WORK ARRAYS OF N ELEMENTS EACH
C  IMULT = NO. OF MATRIX MULTIPLICATIONS ALLOWED (INPUT) OR USED (OUT)
C  STEP 0
      INTEGER N,IPR,IMULT,LIMIT,I,ITN,COUNT
      REAL TOL,G2,G2L,K,T2,B(N),C(N),G(N),T(N),V(N)
      LIMIT=IMULT
      IMULT=0
C  STEP 1
   5  IMULT=IMULT+1
      IF(IMULT.GT.LIMIT)RETURN
      CALL APR(N,B,G)
      DO 10 I=1,N
        G(I)=G(I)-C(I)
  10  CONTINUE
C  STEP 2
  20  G2=0.0
      DO 25 I=1,N
        G2=G2+G(I)**2
        T(I)=-G(I)
  25  CONTINUE
      IF(IPR.GT.0)WRITE(IPR,950)IMULT,G2
 950  FORMAT(13H AFTER STEP 2,I4,15H PRODUCTS, RSS=,1PE16.8)
C  STEP 3
      IF(G2.LT.TOL)RETURN
C  STEP 4
      DO 110 ITN=1,N
C  STEP 5
        IMULT=IMULT+1
        IF(IMULT.GT.LIMIT)RETURN
      CALL APR(N,T,V)
C  STEP 6
        T2=0.0
        DO 60 I=1,N
          T2=T2+T(I)*V(I)
  60    CONTINUE
C  STEP 7
        K=G2/T2
        G2L=G2
C  STEP 8
        G2=0.0
        COUNT=0
        DO 80 I=1,N
          G(I)=G(I)+K*V(I)
          T2=B(I)
          B(I)=T2+K*T(I)
          IF(T2.EQ.B(I))COUNT=COUNT+1
          G2=G2+G(I)**2
  80    CONTINUE
C  STEP 9
      IF(COUNT.EQ.N)GOTO 5
C     IF(COUNT.EQ.N)GOTO 20
C       IF(G2.LT.TOL)RETURN
C   USING ALTERNATIVE STEP 9 ROUTE
        IF(G2.LT.TOL)GOTO 5
      IF(IPR.GT.0)WRITE(IPR,951)IMULT,G2
 951  FORMAT(13H AFTER STEP 9,I4,15H PRODUCTS, RSS=,1PE16.8)
C  STEP 10
        T2=G2/G2L
        DO 100 I=1,N
          T(I)=T2*T(I)-G(I)
 100    CONTINUE
C  STEP 11
 110  CONTINUE
C  STEP 12
      GOTO 5
C  NO STEP 13 SINCE RETURN USED
      END
      SUBROUTINE FRANK(N,T,V)
C  J.C. NASH   JULY 1978, APRIL 1989
      INTEGER N,I,J
      REAL T(N),V(N),S
      DO 10 I=1,N
        S=0.0
        DO 5 J=1,N
          S=S+AMIN0(I,J)*T(J)
   5    CONTINUE
        V(I)=S
  10  CONTINUE
      RETURN
      END

