      SUBROUTINE A22CGM(N,B,FUN,DER,NOCOM,IPR,IFN,IG,EPS,G,X,T,C,P0)
C  ALGORITHM 22 CONJUGATE GRADIENTS FUNCTION MINIMISATION
C  J.C. NASH   JULY 1978, FEBRUARY 1980, APRIL 1989
C  MINIMISE FUNCTION  FUN(N,B,NOCOM) W.R.T. B(I),I=1,2,...,N
C  NOCOM IS A LOGICAL FLAG SET .TRUE. IF INITIAL POINT INFEASIBLE
C  B  IS INITIAL POINT & FINAL APPROXIMATE MINIMUM
C  FUN & DER ARE THE NAMES OF FUNCTION AND DERIVATIVE SUB-PROGRAMS
C     SEE  BELOW FOR CALLING SEQUENCES
C  IPR IS PRINT CHANNEL    IPR.GT.0  FOR PRINTING
C  IFN IS NUMBER OF FN EVALUATIONS USED (OUTPUT)
C      IS LIMIT ON EVALUATIONS (INPUT)
C  IG  IS NUMBER OF DERIVATIVE EVALUATIONS
C  EPS IS MACHINE PRECISION
C  G,X,T,C ARE WORKING VECTORS
C  STEP 0
      LOGICAL NOCOM, ACCPNT
      INTEGER N,IPR,IFN,LIM,IG,COUNT,ITN,I,IFNL
      REAL B(N),X(N),G(N),T(N),C(N),P1,P0,P,G1,G2,K,MSTEP,STEP,EPS,TOL
      REAL A1,A2,T2,GRPR,G3,LSTEP,RELTST,ACCTOL,STREDN,NUSTEP,SETSTP
      STREDN=0.2
      ACCTOL=0.0001
      RELTST=10.0
      SETSTP=1.7
      LIM=IFN
      IFN=0
      IG=0
      TOL=N*EPS*SQRT(EPS)
      LSTEP=1.0
C  STEP 1
      NOCOM=.FALSE.
      P0=FUN(N,B,NOCOM)
      IF(NOCOM)RETURN
      IFN=IFN+1
C  STEP 2
  20  DO 25 I=1,N
        C(I)=0.0
        T(I)=0.0
  25  CONTINUE
C  STEP 3
  30  DO 270 ITN=1,N
        IF(IPR.GT.0)WRITE(IPR,973)IFN,IG,P0
 973    FORMAT( 1H ,I4,11H FUNCTION &,I4,32H DERIVATIVE EVALUATIONS --
     * P0=,1PE16.8)
C  STEP 4
        CALL DER(N,B,G)
        IG=IG+1
C  STEP 5
        G1=0.0
        G2=0.0
        DO 55 I=1,N
          X(I)=B(I)
C****  POLAK RIBIERE FORMULAS
C****            G1=G1+G(I)*(G(I)-C(I))
C****            G2=G2+C(I)**2
C****  FLETCHER REEVES FORMULAS -- CURRENTLY ACTIVE
          G1=G1+G(I)*G(I)
          G2=G2+C(I)*C(I)
C****  BEALE SORENSON FORMULAS
C****          G1=G1+G(I)*(G(I)-C(I))
C****          G2=G2+T(I)*(G(I)-C(I))
          C(I)=G(I)
  55    CONTINUE
C  STEP 6
        IF(G1.GT.TOL)GOTO 70
C  CHECK NOT G2, ALSO SIGN
C
        IF(ITN.EQ.1)RETURN
C  STEP 7
        G3=1.0
  70    IF(G2.GT.0.0)G3=G1/G2
C        WRITE(IPR,8003)G1,G2,G3
C 8003   FORMAT(' G1,G2,G3 ',1P3E16.8)
C  STEP 8
        GRPR=0.0
        T2=0.0
        DO 85 I=1,N
          T(I)=T(I)*G3-G(I)
          T2=T2+T(I)**2
          GRPR=GRPR+T(I)*G(I)
  85    CONTINUE
C        WRITE(IPR,8001)T2,GRPR
C 8001   FORMAT(' AT 85 T2=',1PE16.8,'   GRPR=',E16.8)
C  STEP 9
        STEP=LSTEP
C****  STEP ALONG SEARCH DIRECTION -- STEP 10
        ACCPNT=.FALSE.
C   DON'T HAVE A GOOD POINT YET
        IFNL=IFN
C   RECORDS LAST FUNCTION COUNT
C  STEP 10
  90    COUNT=0
        DO 105 I=1,N
          B(I)=X(I)+STEP*T(I)
          IF(RELTST+B(I).EQ.RELTST+X(I))COUNT=COUNT+1
 105    CONTINUE
C  STEP 11
C        WRITE(IPR,8002)COUNT
C 8002   FORMAT(' AT 105 COUNT =',I4)
        IF(COUNT.LT.N)GOTO 120
        IF(IFN.GT.IFNL)GOTO 120
        STEP=10.0*STEP
C ??? NEED TO GET RID OF UNUSED VARIABLES
C      STEP IS TOO SMALL ON FIRST TRY
       GOTO 90
C  STEP 12
 120   P=FUN(N,B,NOCOM)
       IFN=IFN+1
       ACCPNT = (.NOT.NOCOM).AND.(P.LE.P0+GRPR*STEP*ACCTOL)
       IF (ACCPNT) GOTO 160
       STEP=STREDN*STEP
       WRITE(IPR,974)
  974  FORMAT(1H+,'*')
       GOTO 90
  160  NUSTEP=2.0*((P-P0)-GRPR*STEP)
       IF(NUSTEP.LE.0.0) GOTO 195
       NUSTEP=-GRPR*STEP*STEP/NUSTEP
       DO 170 I=1,N
          B(I)=X(I)+NUSTEP*T(I)
  170  CONTINUE
       P0=P
       NOCOM=.FALSE.
       P=FUN(N,B,NOCOM)
       IFN=IFN+1
C  ??? CHECK NOCOMP ???
       IF(P.GE.P0)GOTO 180
       P0=P
       WRITE(IPR,975)
C  975  FORMAT(1H+,' I< ')
  975  FORMAT(' INTERPOLATION SUCCEEDED')
       GOTO 195
  180  DO 190 I=1,N
         B(I)=X(I)+STEP*T(I)
C      RESETS THE PARAMETERS TO THEIR 'BEST' VALUES
  190  CONTINUE
       WRITE(IPR,976)
  976  FORMAT(' INTERPOLATION FAILED')
C  976  FORMAT(1H+,' I> ')
  195  LSTEP=SETSTP*STEP
       IF(LSTEP.GT.1.0)LSTEP=1.0
C  CAN PLACE A LIMIT ON FUNCTION EVALUATIONS HERE
C  modification 2021-2-12. Chance IFN to -IFN       
       IF(IFN.LT.LIM) GOTO 270
       IFN=-IFN
       RETURN
 270  CONTINUE
C END OF INNER CYCLE
      GOTO 20
      END

